services:

  frontend-build:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/output

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/